# Generated by Django 3.2.9 on 2021-12-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_posted',
            new_name='author',
        ),
    ]
